'use client';

import { useQuery } from '@tanstack/react-query';
import { BarChart3, TrendingUp, DollarSign, Loader2 } from 'lucide-react';
import { supabase } from '@/lib/supabase/client';

interface RoiRow {
  cip_no: string;
  title: string | null;
  stage: string;
  cip_revenue: number | null;
  customer_savings: number | null;
  health_score_delta: number | null;
  resolved_at: string | null;
}

function formatCurrency(n: number | null | undefined): string {
  if (n === null || n === undefined) return '—';
  if (n >= 1_000_000) return `$${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `$${(n / 1_000).toFixed(0)}K`;
  return `$${n.toFixed(0)}`;
}

export function CipRoiPanel() {
  const { data, isLoading } = useQuery({
    queryKey: ['intel', 'roi'],
    queryFn: async () => {
      const { data: rows, error } = await supabase
        .from('cip_items')
        .select('cip_no, title, stage, cip_revenue, customer_savings, health_score_delta, resolved_at')
        .order('resolved_at', { ascending: false, nullsFirst: false })
        .limit(50);
      if (error) throw error;
      return (rows ?? []) as RoiRow[];
    },
  });

  const totals = (data ?? []).reduce(
    (acc, r) => ({
      revenue: acc.revenue + (r.cip_revenue ?? 0),
      savings: acc.savings + (r.customer_savings ?? 0),
      count: acc.count + 1,
    }),
    { revenue: 0, savings: 0, count: 0 },
  );

  if (isLoading) {
    return (
      <div className="flex items-center justify-center p-12">
        <Loader2 className="h-6 w-6 animate-spin text-muted-foreground" />
      </div>
    );
  }

  return (
    <div className="space-y-4 p-6">
      <header>
        <h2 className="font-headline text-xl font-bold tracking-tight">CIP ROI</h2>
        <p className="text-sm text-muted-foreground">
          Revenue and customer savings generated by completed CIPs.
        </p>
      </header>

      <div className="grid gap-3 sm:grid-cols-3">
        <div className="rounded-2xl border border-outline-variant/30 bg-card p-5 shadow-[0_2px_12px_rgba(0,0,0,0.04)]">
          <div className="mb-2 flex items-center gap-2 text-on-primary-fixed-variant">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary-fixed">
              <DollarSign className="h-4 w-4" />
            </div>
            <span className="text-xs font-medium text-muted-foreground">CIP revenue</span>
          </div>
          <div className="font-headline text-2xl font-bold tracking-tight">
            {formatCurrency(totals.revenue)}
          </div>
        </div>

        <div className="rounded-2xl border border-outline-variant/30 bg-card p-5 shadow-[0_2px_12px_rgba(0,0,0,0.04)]">
          <div className="mb-2 flex items-center gap-2 text-on-primary-fixed-variant">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary-fixed">
              <TrendingUp className="h-4 w-4" />
            </div>
            <span className="text-xs font-medium text-muted-foreground">Customer savings</span>
          </div>
          <div className="font-headline text-2xl font-bold tracking-tight">
            {formatCurrency(totals.savings)}
          </div>
        </div>

        <div className="rounded-2xl border border-outline-variant/30 bg-card p-5 shadow-[0_2px_12px_rgba(0,0,0,0.04)]">
          <div className="mb-2 flex items-center gap-2 text-on-primary-fixed-variant">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary-fixed">
              <BarChart3 className="h-4 w-4" />
            </div>
            <span className="text-xs font-medium text-muted-foreground">CIPs tracked</span>
          </div>
          <div className="font-headline text-2xl font-bold tracking-tight">{totals.count}</div>
        </div>
      </div>

      <div className="rounded-2xl border border-outline-variant/30 bg-card shadow-[0_2px_12px_rgba(0,0,0,0.04)]">
        <h3 className="border-b border-outline-variant/30 px-5 py-3 font-headline text-sm font-semibold">
          Recent CIPs
        </h3>
        <table className="w-full text-xs">
          <thead className="text-left text-[10px] uppercase tracking-wider text-muted-foreground">
            <tr>
              <th className="px-5 py-2">CIP</th>
              <th className="px-3 py-2">Title</th>
              <th className="px-3 py-2">Stage</th>
              <th className="px-3 py-2 text-right">Revenue</th>
              <th className="px-3 py-2 text-right">Savings</th>
              <th className="px-5 py-2 text-right">Health Δ</th>
            </tr>
          </thead>
          <tbody>
            {(data ?? []).length === 0 && (
              <tr>
                <td colSpan={6} className="p-5 text-center text-muted-foreground">
                  No CIP data yet. Once CIPs are completed, ROI metrics will appear here.
                </td>
              </tr>
            )}
            {(data ?? []).map((r) => (
              <tr key={r.cip_no} className="border-t border-outline-variant/20">
                <td className="px-5 py-2 font-mono">{r.cip_no}</td>
                <td className="max-w-xs truncate px-3 py-2">{r.title ?? '—'}</td>
                <td className="px-3 py-2 text-muted-foreground">{r.stage}</td>
                <td className="px-3 py-2 text-right">{formatCurrency(r.cip_revenue)}</td>
                <td className="px-3 py-2 text-right">{formatCurrency(r.customer_savings)}</td>
                <td className="px-5 py-2 text-right">
                  {r.health_score_delta !== null
                    ? (r.health_score_delta > 0 ? '+' : '') + r.health_score_delta.toFixed(1)
                    : '—'}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
