import type { TcodeConfig, TcodeKey } from "./types"

const SHARED_LOOKUPS_EQUIPMENT = [
  { table: "lu_countries", rpcFunction: "upsert_lookup_countries_batch", codeColumn: "Country", nameColumn: "Country Name", extraColumns: { name_ko: "Country Name" } },
  { table: "lu_business_types", rpcFunction: "upsert_lookup_batch", codeColumn: "Business Type", nameColumn: "Business Type Name" },
  { table: "lu_platforms", rpcFunction: "upsert_lookup_batch", codeColumn: "Platform Code", nameColumn: "Platform Name" },
  { table: "lu_segments", rpcFunction: "upsert_lookup_batch", codeColumn: "Segment.", nameColumn: "Segment Name" },
  { table: "lu_models", rpcFunction: "upsert_lookup_models_batch", codeColumn: "Model", nameColumn: "Model Name", extraColumns: { segment_code: "Segment.", platform_code: "Platform Code" } },
  { table: "lu_customers", rpcFunction: "upsert_lookup_customers_batch", codeColumn: "Customer", nameColumn: "Customer Name", extraColumns: { country_code: "Country" } },
  { table: "lu_customer_lines", rpcFunction: "upsert_lookup_customer_lines_batch", codeColumn: "Customer Line", nameColumn: "Customer Line Name", extraColumns: { customer_code: "Customer" } },
  { table: "lu_work_centers", rpcFunction: "upsert_lookup_work_centers_batch", codeColumn: "Work Center", nameColumn: "Work Center Name", extraColumns: { plant: "Maintenance Plant." } },
  { table: "lu_sales_modes", rpcFunction: "upsert_lookup_batch", codeColumn: "Sales Mode", nameColumn: "Sales Mode name" },
]

export const TCODE_CONFIGS: Record<TcodeKey, TcodeConfig> = {
  ZCSR0010: {
    tcode: "ZCSR0010",
    label: "ZCSR0010 장비마스터",
    description: "Equipment Master - 장비 기본 정보",
    targetTable: "equipment",
    rpcFunction: "upsert_equipment_batch",
    csvHeaderMap: {
      "Equip. No.": "equip_no",
      "FSC": "fsc",
      "Upper. Equip. No.": "upper_equip_no",
      "A/S BOM": "as_bom",
      "Manu.Serial": "manu_serial",
      "W/O": "wo",
      "Maintenance Plant.": "plant",
      "Work Center": "work_center_code",
      "Work Center Name": "_wc_name",
      "Customer": "customer_code",
      "Customer Name": "_cust_name",
      "Customer Line": "customer_line_code",
      "Customer Line Name": "_cl_name",
      "Business Type": "business_type_code",
      "Business Type Name": "_bt_name",
      "Platform Code": "platform_code",
      "Platform Name": "_pf_name",
      "Segment.": "segment_code",
      "Segment Name": "_seg_name",
      "Model": "model_code",
      "Model Name": "_model_name",
      "Country": "country_code",
      "Country Name": "_country_name",
      "Equip. ID": "equip_id",
      "Shipping Date": "shipping_date",
      "FAB In Date": "fab_in_date",
      "Sign Off Date": "sign_off_date",
      "Warranty Start Date": "warranty_start",
      "Warranty End Date": "warranty_end",
      "W/O Type": "wo_type_code",
      "W/O Type Name": "wo_type_name",
      "Sales Mode": "sales_mode_code",
      "Sales Mode name": "_sm_name",
      "LP(Load Port)": "lp_load_port",
      "EFEM Robot": "efem_robot",
      "TM Robot": "tm_robot",
      "CTC S/W Code": "ctc_sw_code",
      "CTC S/W": "ctc_sw",
      "EFEM S/W Code": "efem_sw_code",
      "EFEM S/W": "efem_sw",
      "Remark1": "remark1",
      "Remark2": "remark2",
      "Remark3": "remark3",
      "Maint Y/N": "maint_yn",
      "\uD604\uC7AC\uACE0\uAC1D": "current_customer",
      "\uC774\uB984 1": "current_customer_name",
      "STAND_ALONE": "stand_alone",
      "W/O\uAD6C\uBD84": "wo_category_code",
      "W/O\uAD6C\uBD84 \uBA85": "wo_category_name",
      "Created On": "created_on",
      "Status": "status",
    },
    transformations: {
      as_bom: "booleanYN",
      maint_yn: "booleanYN",
      shipping_date: "date",
      fab_in_date: "date",
      sign_off_date: "date",
      warranty_start: "date",
      warranty_end: "date",
      created_on: "date",
    },
    lookupExtractions: SHARED_LOOKUPS_EQUIPMENT,
  },

  ZCSR0070D: {
    tcode: "ZCSR0070D",
    label: "ZCSR0070D 서비스오더",
    description: "Service Orders - 정비 작업 오더",
    targetTable: "service_orders",
    rpcFunction: "upsert_service_orders_batch",
    csvHeaderMap: {
      "Service Order No": "order_no",
      "Order Status": "order_status_code",
      "Order Status Text": "order_status_name",
      "Order type": "order_type_code",
      "Order type Text": "order_type_name",
      "Equip. No.": "equip_no",
      "SAP Equip. No.": "sap_equip_no",
      "W/O": "wo",
      "Equip. ID": "equip_id",
      "Country Code": "country_code",
      "Country": "_country_name",
      "Business Type Code": "business_type_code",
      "Business type": "_bt_name",
      "Customer": "customer_code",
      "Customer Name": "_cust_name",
      "Customer Line": "customer_line_code",
      "Customer Line Name": "_cl_name",
      "Model": "model_code",
      "Model Name": "_model_name",
      "Order Title": "order_title",
      "Total Task": "total_task",
      "Complete Work Task": "complete_task",
      "Status(%)": "status_pct",
      "Total Working Time(MIN)": "total_working_time_min",
      "Act Type": "act_type_code",
      "Act Type Name": "_act_name",
      "Cost Type": "cost_type_code",
      "Cost Type Name": "_cost_name",
      "Warranty Code": "warranty_code",
      "Warranty": "_warranty_name",
      "Create by": "created_by",
      "Create User": "created_by_name",
      "Confirmer": "confirmer",
      "Confirmer Name": "confirmer_name",
      "Priority": "priority_code",
      "Priority Name": "_priority_name",
      "Customer Contack": "customer_contact",
      "Work Center": "work_center_code",
      "Work Center Name": "_wc_name",
      "Defect code": "defect_code",
      "Defect code name": "defect_code_name",
      "Defect text": "defect_text",
      "Cause code": "cause_code",
      "Cause code text": "cause_code_name",
      "Cause text": "cause_text",
      "Alarm code": "alarm_code",
      "Plan Start Date": "plan_start_date",
      "Plan End Date": "plan_end_date",
      "Create At": "created_at",
      "Reception Date": "reception_date",
      "Approval Date": "approval_date",
      "Work Start Date": "work_start_date",
      "Work End Date": "work_end_date",
      "Down Time (YYYYMMDD)": "down_time_date",
      "Down Time (HHMMSS)": "down_time_time",
      "Up Time (YYYYMMDD)": "up_time_date",
      "Up Time (HHMMSS)": "up_time_time",
      "Breakdown": "breakdown",
      "Duration": "duration",
      "Unit": "duration_unit",
      "Plant": "plant",
      "Rework": "rework",
      "Year": "year",
      "Month": "month",
      "Title Sort": "title_sort",
      "True/False": "title_true_false",
      "Module": "module",
      "Chamber": "chamber",
      "Position": "position",
      "Part Name": "part_name",
      "Work type": "work_type",
      "Rework Check": "rework_check",
      "Billing": "billing",
      "\uC0C1\uD0DC": "status",
    },
    transformations: {
      total_task: "integer",
      complete_task: "integer",
      status_pct: "commaNumber",
      total_working_time_min: "commaNumber",
      duration: "commaNumber",
      year: "integer",
      rework: "booleanTF",
      title_true_false: "booleanTF",
      plan_start_date: "date",
      plan_end_date: "date",
      created_at: "date",
      reception_date: "date",
      approval_date: "date",
      work_start_date: "date",
      work_end_date: "date",
      down_time_time: "koreanTime",
      up_time_time: "koreanTime",
    },
    lookupExtractions: [
      { table: "lu_countries", rpcFunction: "upsert_lookup_countries_batch", codeColumn: "Country Code", nameColumn: "Country", extraColumns: { name_ko: "Country" } },
      { table: "lu_business_types", rpcFunction: "upsert_lookup_batch", codeColumn: "Business Type Code", nameColumn: "Business type" },
      { table: "lu_customers", rpcFunction: "upsert_lookup_customers_batch", codeColumn: "Customer", nameColumn: "Customer Name", extraColumns: { country_code: "Country Code" } },
      { table: "lu_customer_lines", rpcFunction: "upsert_lookup_customer_lines_batch", codeColumn: "Customer Line", nameColumn: "Customer Line Name", extraColumns: { customer_code: "Customer" } },
      { table: "lu_models", rpcFunction: "upsert_lookup_models_batch", codeColumn: "Model", nameColumn: "Model Name" },
      { table: "lu_work_centers", rpcFunction: "upsert_lookup_work_centers_batch", codeColumn: "Work Center", nameColumn: "Work Center Name", extraColumns: { plant: "Plant" } },
      { table: "lu_act_types", rpcFunction: "upsert_lookup_batch", codeColumn: "Act Type", nameColumn: "Act Type Name" },
      { table: "lu_cost_types", rpcFunction: "upsert_lookup_batch", codeColumn: "Cost Type", nameColumn: "Cost Type Name" },
      { table: "lu_warranty_codes", rpcFunction: "upsert_lookup_batch", codeColumn: "Warranty Code", nameColumn: "Warranty" },
      { table: "lu_priorities", rpcFunction: "upsert_lookup_batch", codeColumn: "Priority", nameColumn: "Priority Name" },
      { table: "lu_defect_codes", rpcFunction: "upsert_lookup_batch", codeColumn: "Defect code", nameColumn: "Defect code name" },
      { table: "lu_cause_codes", rpcFunction: "upsert_lookup_batch", codeColumn: "Cause code", nameColumn: "Cause code text" },
      { table: "lu_order_types", rpcFunction: "upsert_lookup_batch", codeColumn: "Order type", nameColumn: "Order type Text" },
    ],
  },

  ZCSR0070D_TASK: {
    tcode: "ZCSR0070D_TASK",
    label: "ZCSR0070D_TASK 태스크상세",
    description: "Service Tasks - 태스크별 작업자 로그 (ZCSR0140D)",
    targetTable: "service_tasks",
    rpcFunction: "upsert_service_tasks_batch",
    csvHeaderMap: {
      "Service Order No": "order_no",
      "Task No.": "task_no",
      "Standard Text key": "task_code",
      "Description": "task_name",
      "Task Status": "task_status",
      "ID Category": "id_category",
      "ID Category Name": "id_category_name",
      "Partner Company": "partner_company",
      "Partner Company Name": "partner_company_name",
      "ID": "worker_id",
      "Name": "worker_name",
      "Main": "is_main",
      "Engineer Level": "engineer_level",
      "Record date": "record_date",
      "Work Start Date": "work_start_date",
      "Work Start Time": "work_start_time",
      "Work End Date": "work_end_date",
      "Work End Time": "work_end_time",
      "Work Time": "work_time_min",
      "Non Work Time": "non_work_time_min",
      "Total(MIN)": "total_min",
      "Moving Time": "moving_time_min",
      "Unit": "time_unit",
      "Total(Hour)": "total_hour",
      "Remark": "remark",
      "Act Type": "act_type_code",
      "Act Type Name": "_act_name",
      "Cost Type": "cost_type_code",
      "Cost Type Name": "_cost_name",
      "Warranty Code": "warranty_code",
      "Warranty": "_warranty_name",
      "Priority": "priority_code",
      "Priority Name": "_priority_name",
      "Work Center": "work_center_code",
      "Work Center Name": "_wc_name",
      "Equip. No.": "equip_no",
      "Equip. ID": "equip_id",
      "SAP Equip. No.": "sap_equip_no",
      "Material No.": "material_no",
      "Material description": "material_desc",
      "W/O": "wo",
      "Country": "country_code",
      "Business Type Code": "business_type_code",
      "Customer": "customer_code",
      "Customer Line": "customer_line_code",
      "Model": "model_code",
      "Order Title": "order_title",
      "Plant": "plant",
      "Year": "year",
      "Month": "month",
      "Working hour": "working_hour",
      "Worker": "worker_key",
      "Company": "company",
      "Create At": "_create_at",
      "\uC0C1\uD0DC": "status",
    },
    transformations: {
      is_main: "booleanTF",
      record_date: "date",
      work_start_date: "date",
      work_start_time: "koreanTime",
      work_end_date: "date",
      work_end_time: "koreanTime",
      work_time_min: "integer",
      non_work_time_min: "integer",
      total_min: "integer",
      moving_time_min: "integer",
      total_hour: "commaNumber",
      working_hour: "commaNumber",
      year: "integer",
      month: "integer",
    },
    lookupExtractions: [
      { table: "lu_task_codes", rpcFunction: "upsert_lookup_batch", codeColumn: "Standard Text key", nameColumn: "Description" },
      { table: "lu_act_types", rpcFunction: "upsert_lookup_batch", codeColumn: "Act Type", nameColumn: "Act Type Name" },
      { table: "lu_cost_types", rpcFunction: "upsert_lookup_batch", codeColumn: "Cost Type", nameColumn: "Cost Type Name" },
      { table: "lu_warranty_codes", rpcFunction: "upsert_lookup_batch", codeColumn: "Warranty Code", nameColumn: "Warranty" },
      { table: "lu_priorities", rpcFunction: "upsert_lookup_batch", codeColumn: "Priority", nameColumn: "Priority Name" },
      { table: "lu_work_centers", rpcFunction: "upsert_lookup_work_centers_batch", codeColumn: "Work Center", nameColumn: "Work Center Name", extraColumns: { plant: "Plant" } },
    ],
  },

  ZCSR0100: {
    tcode: "ZCSR0100",
    label: "ZCSR0100 파트사용이력",
    description: "Part Usage - 파트 교체/사용 이력",
    targetTable: "part_usage",
    rpcFunction: "upsert_part_usage_batch",
    csvHeaderMap: {
      "Serivce Order No": "order_no",
      "A/S BOM Check": "as_bom_check",
      "Usage type": "usage_type",
      "Supply Type": "supply_type",
      "Supply Description": "supply_desc",
      "Part No.": "part_no",
      "Part Name": "part_name",
      "Part Spec": "part_spec",
      "KEY": "is_key_part",
      "RTN": "is_return",
      "Used Qty": "used_qty",
      "Unit": "unit",
      "Serial Number": "serial_number",
      "RF Time(New)": "rf_time_new",
      "Part Model": "part_model",
      "Location Group": "location_group",
      "Location Code": "location_code",
      "Location Description": "location_desc",
      "Damage Group": "damage_group",
      "Damage Code": "damage_code",
      "Damage Gescription": "damage_desc",
      "Activity Group": "activity_group",
      "Activity Code": "activity_code",
      "Activity Description": "activity_desc",
      "Remark": "remark",
      "Order status code": "order_status_code",
      "Order status": "_order_status_name",
      "title": "order_title",
      "Country code": "country_code",
      "Country description": "_country_name",
      "W/O": "wo",
      "Customer line": "customer_line_code",
      "Customer line Description": "_cl_name",
      "Business Type": "business_type_code",
      "Business Type Description": "_bt_name",
      "Platform Code": "platform_code",
      "Platform Name": "_pf_name",
      "Segment.": "segment_code",
      "Segment Name": "_seg_name",
      "Model": "model_code",
      "Model Name": "_model_name",
      "Task no": "task_no",
      "Task code": "task_code",
      "Task name": "task_name",
      "Equip. No": "equip_no",
      "Equip. ID": "equip_id",
      "Sales mode": "sales_mode_code",
      "Sales mode Description": "_sm_name",
      "Create by": "created_by",
      "Create by Name": "created_by_name",
      "Approved Date": "approved_date",
      "Warranty code group": "_warranty_group",
      "Warranty code": "warranty_code",
      "Warranty code Description": "_warranty_name",
      "Warranty Start": "warranty_start",
      "Warranty End": "warranty_end",
      "Part Path": "part_path",
      "Changed Part No.": "changed_part_no",
      "Changed  Part Name": "changed_part_name",
      "Changed Part Spec": "changed_part_spec",
      "Changed KEY": "changed_key",
      "Changed RTN": "changed_return",
      "Changed part Model": "changed_part_model",
      "Changed  Qty": "changed_qty",
      "Changed Part Unit": "changed_unit",
      "Changed Part Serial Number": "changed_serial",
      "RF Time(Old)": "rf_time_old",
      "\uC0AC\uC6A9\uC77C\uC790": "usage_date",
      "Material Group(New)": "material_group_new",
      "Material Group Name(New)": "material_group_new_name",
      "Material Group(Old)": "material_group_old",
      "Material Group Name(Old)": "material_group_old_name",
      "Plant": "plant",
    },
    transformations: {
      is_key_part: "booleanYN",
      is_return: "booleanYN",
      changed_key: "booleanYN",
      changed_return: "booleanYN",
      used_qty: "integer",
      changed_qty: "integer",
      rf_time_new: "commaNumber",
      rf_time_old: "commaNumber",
      usage_date: "date",
      approved_date: "date",
      warranty_start: "date",
      warranty_end: "date",
    },
    lookupExtractions: [
      { table: "lu_damage_codes", rpcFunction: "upsert_lookup_with_group_batch", codeColumn: "Damage Code", nameColumn: "Damage Gescription", extraColumns: { group_code: "Damage Group" } },
      { table: "lu_activity_codes", rpcFunction: "upsert_lookup_with_group_batch", codeColumn: "Activity Code", nameColumn: "Activity Description", extraColumns: { group_code: "Activity Group" } },
      { table: "lu_material_groups", rpcFunction: "upsert_lookup_batch", codeColumn: "Material Group(New)", nameColumn: "Material Group Name(New)" },
    ],
  },

  ZCSR0150: {
    tcode: "ZCSR0150",
    label: "ZCSR0150 월별가동이력",
    description: "Equipment Monthly Metrics - 설비 가동시간 (피벗→언피벗)",
    targetTable: "equipment_monthly_metrics",
    rpcFunction: "upsert_equipment_monthly_metrics_batch",
    csvHeaderMap: {
      "SAP Equip. No.": "sap_equip_no",
      "W/O": "wo",
      "Equip. ID": "equip_id",
      "Manu.Equip.No.": "equip_no",
      "Plant": "plant",
      "Work Center": "work_center_code",
      "Country": "country_code",
      "Business Type Code": "business_type_code",
      "Customer": "customer_code",
      "Customer Line": "customer_line_code",
      "Platform Code": "platform_code",
      "Segment.": "segment_code",
      "Model": "model_code",
      "Sales mode": "sales_mode_code",
      "Status": "equip_status_code",
      "Status Name": "equip_status_name",
      "Division": "division",
    },
    transformations: {},
    lookupExtractions: [],
    isUnpivot: true,
    unpivotConfig: {
      fixedColumns: [
        "SAP Equip. No.", "W/O", "Equip. ID", "Manu.Equip.No.", "Plant",
        "Work Center", "Work Center Name", "Country", "Country Name",
        "Business Type Code", "Business Type", "Customer", "Customer Name",
        "Customer Line", "Customer Line Name", "Platform Code", "Platform Name",
        "Segment.", "Segment Name", "Model", "Model Name",
        "Shipping Date", "FAB In", "Sign Off", "Warranty start date", "Warranty end date",
        "Sales mode", "Sales mode Name", "Status", "Status Name",
        "\uC0C1\uD0DC",
      ],
      divisionColumn: "Division",
      monthColumnPattern: /^\d{6}$/,
    },
  },
}

export function getTcodeConfig(tcode: TcodeKey): TcodeConfig {
  return TCODE_CONFIGS[tcode]
}

export const TCODE_IMPORT_ORDER: TcodeKey[] = [
  "ZCSR0010",
  "ZCSR0070D",
  "ZCSR0070D_TASK",
  "ZCSR0100",
  "ZCSR0150",
]
